name: Build
run-name: lint and bundle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node up
        uses: actions/setup-node@v3

      - name: enable corepack
        run: corepack enable

      - name: install
        run: yarn

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: upload files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
